### ISSUE TITLE
并查集基础学习笔记 - NSObject.23786 的博客

### ISSUE THREAD

**Issue by AFObject** [AFObject/OI-Blog#11]
http://www.nsobjectzyx.tk/2020/11/28/%E5%B9%B6%E6%9F%A5%E9%9B%86%E5%9F%BA%E7%A1%80%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/ 

 Welcome to visit my blog.

**Comment by zxh23682** [comment]
qp%%%
