### ISSUE TITLE
OI in 2020 - NSObject.23786 的博客

### ISSUE THREAD

**Issue by AFObject** [AFObject/OI-Blog#13]
http://www.nsobjectzyx.tk/2020/12/27/OI-in-2020/ 

 Welcome to visit my blog.

**Comment by ioiakzqs** [comment]
我直接膜拜吊打我的NSObject，OI吊打我，其它IT技术方面更吊打我

**Comment by 23786** [comment]
> 我直接膜拜吊打我的NSObject，OI吊打我，其它IT技术方面更吊打我

fAKe 给爷爬，我 OI 和 whk 都菜得一批，IT 这种东西也只是因为感兴趣才去了解了一下

**Comment by ioiakzqs** [comment]
悲剧老D是我的荣幸😍😍😍

总而言之NSObject AKIOI！吊打国家队！

初一PJ1=还不强？OrzOrzOrz

**Comment by ioiakzqs** [comment]
您的blog是WP的吗，好好看😍😍😍

**Comment by 23786** [comment]
> 您的blog是WP的吗，好好看😍😍😍

不是，我在 readme 写了

**Comment by qinyihao** [comment]
我直接膜拜吊打我的NSObject，OI吊打我，其它IT技术方面更吊打我
