### ISSUE TITLE
About - NSObject.23786 的博客

### ISSUE THREAD

**Issue by AFObject** [AFObject/OI-Blog#2]
http://www.nsobjectzyx.tk/about/ 

 Welcome to visit my blog.

**Comment by juruojjl** [comment]
qpzc

**Comment by sunmy2019** [comment]
看到你写的 Cppp 了, 很厉害

我从也是上海的同学 兰生15->华二18->清华

**Comment by 23786** [comment]
> @sunmy2019
> 看到你写的 Cppp 了, 很厉害
> 
> 我从也是上海的同学 兰生15->华二18->清华

谢谢qwq

啊这，其实我个人觉得那个cppp思路有点混乱，正在100%重构代码

**Comment by sunmy2019** [comment]
没事，个人觉得这就是一个玩具，反正没有人会真的用。自己开发着开心就好


CLion 这种真正的 IDE 强大太多了

**Comment by 23786** [comment]
> @sunmy2019
> 没事，个人觉得这就是一个玩具，反正没有人会真的用。自己开发着开心就好。
> 
> 
> 像 CLion 这种真正的 IDE 强大太多了，虽然写 OI 不见得用得上，但是在大型项目中非常牛

~~我会真的用~~

说实话，我现在写OI就只用我自己的这个，有自动补全，顺手

我认为这个做做好给用Mac的搞OI的同学用还是有可能的，只不过离真正的IDE还有很大距离（
