### ISSUE TITLE
CSP 2019 低分代码分析 - NSObject.23786 的博客

### ISSUE THREAD

**Issue by AFObject** [AFObject/OI-Blog#4]
http://www.nsobjectzyx.tk/2020/10/25/CSP-2019-%E4%BD%8E%E5%88%86%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90/ 

 Welcome to visit my blog.

**Comment by 23786** [comment]
谔谔，老师上课讲的

**Comment by RyanJZC** [comment]
......那个没加 `<cstdio>` 的是559?

**Comment by 23786** [comment]
> @RyanJZC
> ......那个没加 `<cstdio>` 的是559?

，，？不知道（

**Comment by juruojjl** [comment]
谔谔

话说您怎么注册twitter的（

**Comment by 23786** [comment]
> @juruojjl
> 谔谔
> 
> 话说您怎么注册twitter的（

珂 学 上 网 即可

不过我这个Twitter号已经废了，登不上去了

**Comment by juruojjl** [comment]
啊啊啊这

**Comment by RyanJZC** [comment]
...用github
